### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by ratbeard** [farhan2986/angular-ui-fuelux-wizard#1]
Please add a LICENSE file, so I can integrate this in to my application.

Thank you!

http://choosealicense.com/licenses/mit/

**Comment by farhan2986** [comment]
added license file. @ratbeard Is this neccessary to add license text in each source file? asking just for the sake of information :)

**Comment by ratbeard** [comment]
Nope, just a single license file in the app root is sufficient.

Thanks for adding it and releasing your code!
